sonar_user: 'sonar_user'
sonar_pass: 'sonar_password'
sonar_base_url: 'http://my-sonar.com.br'
sonar_issue_type: 'VULNERABILITY'
sonar_project: 'project_name'
sonar_branch: 'branch_name'
jira_user: 'jira_user'
jira_pass: 'jira_password'
jira_project: 'jira_project'
jira_base_url: 'https://my-jira.com'
